### ISSUE TITLE
Modified Akima?

### ISSUE THREAD

**Issue by ijustlovemath** [cgohlke/akima#1]
Hi! Is there any chance you could support the modified Akima interpolator, detailed (with code!) here: https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/

I'm going to implement it myself, but in case a Google search lands someone at your library, like it did for me, it would be a nice feature!

**Comment by cgohlke** [comment]
Hi. Interesting. I think these days it would make more sense to contribute it to SciPy: https://docs.scipy.org/doc/scipy/reference/interpolate.html
